# -*- coding: utf-8 -*-
"""Helper: generates self_check_guide.md"""
import sys, os
out_path = sys.argv[1] if len(sys.argv) > 1 else "self_check_guide.md"

content = [
    "# 遮挡验证自检清单",
    "",
    "## 0. 运行脚本",
    "",
    'bash: python "d:/我的文件/研究生学术/光学项目/0506新/ocs_project/05_occlusion_validation/run_occlusion_validation.py"',
    "",
    "输出目录：结果/遮挡验证/run_YYYYMMDD_HHMMSS/",
    "",
    "## 1. 合成验证——快速通过性检查",
    "",
    "打开 validation_summary.csv，确认所有 11 项 status = 符合预期/PASS。",
    "",
    "| 验证项 | 预期命中率 | 含义 |",
    "|---|---|---|",
    "| epsilon=0 单平板 | 1.000 | epsilon=0 时射线起点在面内，应命中自身（暴露自相交） |",
    "| epsilon>0 单平板 | 0.000 | epsilon>0 时偏移离开面，不应命中自身 |",
    "| 双平板跨部件 | 1.000 | 排除下平板后应命中上平板 |",
    "| U型块（排除当前部件） | 0.000 | 当前逻辑整体排除部件，不应命中背墙（漏检，预期行为） |",
    "| U型块（不排除） | 1.000 | 参考逻辑应命中背墙，证明物理遮挡存在 |",
    "| 双圆柱嵌套 | 1.000 | 排除内圆柱后应命中外圆柱 |",
    "",
    "## 2. 汇总图——视觉解读",
    "",
    "打开 figures/summary_pass_fail.png：",
    "- 左柱（绿/红）= 实际命中率  右柱（灰）= 预期命中率",
    "- 绿色 = 实际等于预期，正确    红色 = 不等于预期，错误",
    "- 柱子看不见（高度为0）= 命中率为0，预期为0时正常",
    "- epsilon>0 的单平板柱子和 U型块 current_exclude 柱都是 0（预期行为）",
    "",
    "## 3. epsilon 敏感性——真实模型稳定性",
    "",
    "打开 figures/realmodel_epsilon_sensitivity.png：",
    "- X轴 = epsilon值（mm），对数坐标",
    "- Y轴 = 排除逻辑与参考逻辑不一致的面元数量",
    "- 线条接近0 = 该档位下两种逻辑几乎无差异",
    "- 所有档位都是0 = 该部件在此姿态下无同部件遮挡问题",
    "- 打开 realmodel_epsilon_summary.csv 查阅具体数值",
    "",
    "## 4. 高优先级候选——人工抽查",
    "",
    "打开 manual_review_candidates.csv，筛选 priority = High 的行。",
    "人工确认方法：",
    "1. 打开 figures/realmodel_{part}_annotations.png",
    "2. 找到标注的点号（#1-#6），对应CSV中的面元",
    "3. 判断：该面元沿橙线（太阳）/ 蓝线（探测器）出发，是否被自身部件遮挡",
    "4. 若参考逻辑命中但当前逻辑不命中 = 当前代码会漏检该同部件遮挡",
    "",
    "## 5. 决策树",
    "",
    "检查 epsilon 敏感性图：",
    "- 所有部件差异计数约0 --> 真实模型无同部件遮挡，无需修改",
    "- 部分部件差异计数>0 --> 差异大（>20%）建议修改，差异小（<5%）可按需决定",
    "",
    "## 6. 输出文件索引",
    "",
    "| 文件 | 用途 |",
    "|---|---|",
    "| occlusion_validation_report.md | 完整报告 |",
    "| validation_summary.csv | 11项合成验证原始数据 |",
    "| figures/summary_pass_fail.png | 命中率对比图 |",
    "| realmodel_epsilon_summary.csv | epsilon敏感性统计 |",
    "| figures/realmodel_epsilon_sensitivity.png | epsilon敏感性曲线 |",
    "| manual_review_candidates.csv | 面元详细结果 |",
    "| figures/realmodel_*_annotations.png | 三维标注图 |",
    "| models/*.stl | 合成验证模型 |",
]

with open(out_path, "w", encoding="utf-8") as f:
    f.write("\n".join(content) + "\n")

print(f"Saved: {out_path}")
